version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: getting-started
        ports:
            - 3000:3000
        environment:
            MYSQL_HOST: maria
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: todos

    maria:
        image: mariadb:10
        volumes:
            - todo-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: todos

volumes:
    todo-mysql-data:

